version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: zealthyniti
      POSTGRES_DB: custom_onboarding_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: your_username
      DB_PASSWORD: zealthyniti
      DB_NAME: custom_onboarding_db

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
